# This is a docker compose file for defining and running
# multi-container environments. It simplifies the control
# of your application stack into a single configuration
# file. The following commands are useful:
#
#   docker compose up          - "runs" the entire system
#   docker compose up --build  - force a build and "runs" system
#   docker compose up -d       - "runs" system in detacted mode
#   docker compose down        - "closes" the entire system and deletes everything
#   docker compose stop        - stop running containers without removing them
#   docker compose start       - start previously stopped containers
#
version: '3.9'
name: ms-arch

services:
  registry:
    build:
      context: ./registry
    container_name: registry
    networks:
      - skynet

  service-a:
    build:
      context: ./service-a
    container_name: service-a
    depends_on:
      - registry
    networks:
      - skynet

  service-b:
    build:
      context: ./service-b
    container_name: service-b
    depends_on:
      - registry
    networks:
      - skynet

  service-c:
    build:
      context: ./service-c
    container_name: service-c
    depends_on:
      - registry
    networks:
      - skynet

  service-d:
    build:
      context: ./service-d
    container_name: service-d
    depends_on:
      - registry
    networks:
      - skynet

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    depends_on:
      - service-a
      - service-b
      - service-c
      - service-d
    networks:
      - skynet
    ports:
      - "3000:3000"
  
  service-18:
    build:
      context: ./service-18
    container_name: service-18
    ports:
      - "3018:3018"
    networks:
      - skynet
    depends_on:
      - registry

networks:
  skynet:
    driver: bridge

